[package]
name = "lbf"
version = "0.4.0"
edition = "2024"
license = "MPL-2.0"
repository = "https://github.com/JeroenGar/jagua-rs"
authors = ["Jeroen Gardeyn"]

[dependencies]
jagua-rs-base = { path = "../jagua-rs-base"}
jagua-rs-bpp = { path = "../jagua-rs-bpp"}
jagua-rs-spp = { path = "../jagua-rs-spp"}
rand = { version = "0.9", features = [ "small_rng" ] }
rand_distr = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = { version = "1.20", features = [] }
fern = "0.7"
log = "0.4"
itertools = "0.14"
svg = "0.18"
ordered-float = "5.0.0"
clap = { version = "4.5", features = ["derive"] }
mimalloc = "0.1"
almost = "0.2.0"
test-case = "3.3.1"
thousands = "0.2.0"
jiff = "0.2.4"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "quadtree_bench"
harness = false

[[bench]]
name = "fast_fail_bench"
harness = false

#[[bench]]
#name = "edge_sensitivity_bench"
#harness = false

[profile.release]
opt-level = 3

[profile.test]
debug-assertions = true
opt-level = 3
