[package]
name = "lbf"
version = "0.1.1"
edition = "2021"
license = "Mozilla Public License 2.0"
repository = "https://github.com/JeroenGar/jagua-rs"
authors = ["Jeroen Gardeyn"]

[dependencies]
jagua-rs = { path = "../jagua-rs" , version = "0.1.1", features = ["double-precision"] }
rand = { version = "0.8.5", features = [ "small_rng" ] }
rand_distr = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = { version = "1.19.0", features = [] }
fern = "0.6.2"
log = "0.4.20"
humantime = "2.1.0"
itertools = "0.12.0"
svg = "0.16.0"
ordered-float = "4.2.0"
clap = { version = "4.4.18", features = ["derive"] }
mimalloc = "0.1.39"
tribool = "0.3.0"
almost = "0.2.0"
test-case = "3.3.1"
thousands = "0.2.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "quadtree_bench"
harness = false

[[bench]]
name = "fast_fail_bench"
harness = false

#[[bench]]
#name = "edge_sensitivity_bench"
#harness = false

[[bench]]
name = "hpg_bench"
harness = false

[profile.release]
opt-level = 3

[profile.test]
debug-assertions = true
opt-level = 3
